# Generated by Django 3.2.16 on 2023-02-24 15:56

import apps.goerli.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoerliPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressDelCreador', models.CharField(max_length=52)),
                ('contractAddress', models.CharField(max_length=52, unique=True)),
                ('slug', models.SlugField(max_length=52, unique=True)),
                ('rendimiento', models.PositiveIntegerField()),
                ('terminosYcondiciones', models.TextField()),
                ('fechaDeCreacion', models.DateField(auto_now_add=True)),
                ('cantidadObjetivo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoerliPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressDelCreador', models.CharField(max_length=52)),
                ('contractAddress', models.CharField(max_length=52, unique=True)),
                ('slug', models.SlugField(max_length=52, unique=True)),
                ('rendimiento', models.PositiveIntegerField()),
                ('terminosYcondiciones', models.TextField()),
                ('fechaDeCreacion', models.DateField(auto_now_add=True)),
                ('cantidadObjetivo', models.PositiveIntegerField()),
                ('correoElectronico', models.EmailField(max_length=150, unique=True)),
                ('linkInstagram', models.URLField(blank=True, max_length=250, null=True)),
                ('paginaWeb', models.URLField(blank=True, max_length=250, null=True)),
                ('linkTwitter', models.URLField(blank=True, max_length=250, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=250, null=True)),
                ('oficinas', models.URLField(blank=True, max_length=250, null=True)),
                ('imagenPersonal', models.ImageField(upload_to=apps.goerli.models.public_thumbnail_directory)),
                ('logo', models.ImageField(upload_to=apps.goerli.models.public_thumbnail_directory)),
                ('trayectoria', models.TextField()),
            ],
        ),
    ]
